# Generated by Django 5.0.2 on 2024-03-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SigmaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('day', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Class',
            new_name='Place',
        ),
    ]
