# Generated by Django 5.0.2 on 2024-03-06 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SigmaApp', '0002_activity_rename_class_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='age',
            new_name='hour',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='email',
        ),
    ]
